config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Auth routes
  get "/login", to: "auth/sessions#new", as: "login"
  post "/login", to: "auth/sessions#create"
  get "/logout", to: "auth/sessions#destroy", as: "logout"

  # Admin routes
  namespace :admin do
    resources :pages
    resources :snippets
    resources :article_categories
    resources :articles
    resources :product_categories
    resources :suppliers
    resources :products
    resources :project_categories
    resources :projects
    resources :activities, only: %i[index]
    resources :users
    resources :sortables, only: %i[create]
    resource :profile, only: %i[show update]
    root "dashboard#show"
  end

  # Public routes
  scope "(:locale)", locale: /en|el/ do
    resources :articles, only: [:index]
  end
  get "/:locale", to: "home#show", as: "home"
  root "home#show"
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for([:admin, page]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="fieldset">
    <%= f.input :slug %>
  </div>

  <div class="fieldset">
    <%= f.input :title_en, wrapper_html: { class: "col-span-2" } %>
    <%= f.input :body_en, wrapper: :rich_editor %>
    <%= f.input :description_en, wrapper: :autogrow %>
    <%= f.input :keywords_en, wrapper: :autogrow %>
  </div>

  <div class="fieldset">
    <%= f.input :title_el, wrapper_html: { class: "col-span-2" } %>
    <%= f.input :body_el, wrapper: :rich_editor %>
    <%= f.input :description_el, wrapper: :autogrow %>
    <%= f.input :keywords_el, wrapper: :autogrow %>
  </div>

  <div class="fieldset">
    <%= f.input :images, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save page" %>
    <% if page.new_record? %>
      <%= link_to "Cancel", admin_pages_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", admin_page_path(page), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/pages/_page.html.erb
<%= content_tag :tr, id: dom_id(page), class: dom_class(page) do %>
  <td class="td">
    <%= link_to page.title, admin_page_path(page), class: "link", data: { turbo_frame: "_top" } %>
  </td>
  <td class="td td-time">
    <%= l page.created_at, format: :short %>
  </td>
  <td class="td td-actions">
    <ul class="row-actions">
      <% if policy(page).update? %>
        <li>
          <%= link_to "Edit", edit_admin_page_path(page), class: "link", data: { turbo_frame: "_top" } %>
        </li>
      <% end %>

      <% if policy(page).destroy? %>
        <li>
          <%= button_to "Delete", admin_page_path(page), method: :delete, class: "link link-danger", form: { data: { turbo_confirm: "Are you sure you want to delete this page?" } } %>
        </li>
      <% end %>
    </ul>
  </td>
<% end %>

app/views/admin/pages/edit.html.erb
<header class="page-header">
  <h1><%= title "Editing page" %></h1>
  <%= link_to "Show page", admin_page_path(@page), class: "ml-auto btn btn-primary" %>
</header>

<%= render "form", page: @page %>

app/views/admin/pages/index.html.erb
<header class="page-header">
  <h1><%= title "Pages" %></h1>
  <%= link_to "New page", new_admin_page_path, class: "ml-auto btn btn-primary" if policy(Page).create? %>
</header>

<%= form_with url: "", method: "get", data: { turbo_frame: "pages", turbo_action: "advance", controller: "search" } do |f| %>
  <div class="flex py-3 space-x-2 border-b border-neutral-200 dark:border-neutral-800">
    <%= f.search_field :query, placeholder: "Search...", value: params[:query], class: "field-input", data: { action: "input->search#submit" } %>
  </div>
<% end %>

<%= turbo_frame_tag "pages" do %>
  <% if @pagy.count.zero? %>
    <div class="my-4 h-32 flex flex-col items-center justify-center border-4 border-dashed rounded-md border-neutral-300">
      <p class="text-sm text-neutral-500">
        No pages were found.
        <%= link_to new_admin_page_path, class: "inline-flex link", data: { turbo_frame: "_top" } do %>
          <span>Add a new one</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="ml-1 h-5 w-5 text-indigo-500" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        <% end if policy(Page).create? %>
      </p>
    </div>
  <% else %>
    <table class="table table-index">
      <thead>
        <tr>
          <th class="th">Title</th>
          <th class="th th-time">Created</th>
          <th class="th th-actions">Actions</th>
        </tr>
      </thead>

      <tbody>
        <%= render @pages %>
      </tbody>
    </table>

    <%== pagy_nav(@pagy) %>
  <% end %>
<% end %>

app/views/admin/pages/new.html.erb
<header class="page-header">
  <h1><%= title "New page" %></h1>
</header>

<%= render "form", page: @page %>

app/views/admin/pages/show.html.erb
<header class="page-header">
  <h1><%= title "Page details" %></h1>
  <%= link_to "Edit page", edit_admin_page_path(@page), class: "ml-auto btn btn-primary" if policy(@page).update? %>
  <%= button_to "Delete page", admin_page_path(@page), method: :delete, class: "ml-4 btn btn-danger", form: { data: { turbo_confirm: "Are you sure you want to delete this page?" } } if policy(@page).destroy? %>
</header>

<%= show_for @page do |s| %>
  <%= s.attribute :title_en %>
  <%= s.attribute :body_en do %>
    <%= markdown @page.body_en %>
  <% end %>
  <%= s.attribute :description_en %>
  <%= s.attribute :keywords_en %>
  <%= s.attribute :title_el %>
  <%= s.attribute :body_el do %>
    <%= markdown @page.body_el %>
  <% end %>
  <%= s.attribute :description_el %>
  <%= s.attribute :keywords_el %>
  <%= s.attribute :images do %>
    <%= sortable_thumbnails_for @page %>
  <% end %>
  <%= s.attribute :created_at do %>
    <%= local_time @page.created_at, format: :long %>
  <% end %>
  <%= s.attribute :updated_at do %>
    <%= local_time @page.updated_at, format: :long %>
  <% end %>
  <%= s.attribute :history do %>
    <%= render "admin/activities/history", trackable: @page %>
  <% end %>
<% end %>