config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Auth routes
  get "/login", to: "auth/sessions#new", as: "login"
  post "/login", to: "auth/sessions#create"
  get "/logout", to: "auth/sessions#destroy", as: "logout"

  # Admin routes
  namespace :admin do
    resources :pages
    resources :snippets
    resources :article_categories
    resources :articles
    resources :product_categories
    resources :suppliers
    resources :products
    resources :project_categories
    resources :projects
    resources :activities, only: %i[index]
    resources :users
    resources :sortables, only: %i[create]
    resource :profile, only: %i[show update]
    root "dashboard#show"
  end

  # Public routes
  scope "(:locale)", locale: /en|el/ do
    resources :articles, only: [:index]
  end
  get "/:locale", to: "home#show", as: "home"
  root "home#show"
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < Admin::BaseController
    def show
      authorize(:dashboard)
    end
  end
end

app/views/admin/dashboard/show.html.erb
<header class="page-header border-0">
  <h1><%= title "Dashboard" %></h1>
</header>

<div class="grid sm:grid-cols-3 gap-4">
  <div class="sm:col-span-2 grid sm:grid-cols-2 gap-4">
    <ul class="text-sm divide-y divide-neutral-200 dark:divide-neutral-800">
      <li><h2 class="py-3 text-base">Content</h2></li>
      <li>
        <%= link_to "Pages", admin_pages_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Snippets", admin_snippets_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Article categories", admin_article_categories_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Articles", admin_articles_path, class: "link block py-3" %>
      </li>
    </ul>

    <ul class="text-sm divide-y divide-neutral-200 dark:divide-neutral-800">
      <li><h2 class="py-3 text-base">Business</h2></li>
      <li>
        <%= link_to "Suppliers", admin_suppliers_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Product categories", admin_product_categories_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Products", admin_products_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Project categories", admin_project_categories_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Projects", admin_projects_path, class: "link block py-3" %>
      </li>
    </ul>

    <ul class="text-sm divide-y divide-neutral-200 dark:divide-neutral-800">
      <li><h2 class="py-3 text-base">Advanced</h2></li>
      <li>
        <%= link_to "Activities", admin_activities_path, class: "link block py-3" %>
      </li>
      <li>
        <%= link_to "Users", admin_users_path, class: "link block py-3" %>
      </li>
    </ul>
  </div>

  <div>
    <ul class="text-sm bg-indigo-50 dark:bg-sky-900/50 border border-indigo-100 dark:border-sky-800 rounded-lg divide-y divide-indigo-100 dark:divide-sky-800">
      <li><h2 class="p-3 text-base"><%= Current.user.name %></h2></li>
      <li>
        <%= link_to "Edit your profile", admin_profile_path, class: "link block p-3" %>
      </li>
      <li>
        <%= link_to "Contact administrator", admin_profile_path, class: "link block p-3" %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, class: "link block p-3" %>
      </li>
    </ul>
  </div>
</div>