config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Auth routes
  get "/login", to: "auth/sessions#new", as: "login"
  post "/login", to: "auth/sessions#create"
  get "/logout", to: "auth/sessions#destroy", as: "logout"

  # Admin routes
  namespace :admin do
    resources :pages
    resources :snippets
    resources :article_categories
    resources :articles
    resources :product_categories
    resources :suppliers
    resources :products
    resources :project_categories
    resources :projects
    resources :activities, only: %i[index]
    resources :users
    resources :sortables, only: %i[create]
    resource :profile, only: %i[show update]
    root "dashboard#show"
  end

  # Public routes
  scope "(:locale)", locale: /en|el/ do
    resources :articles, only: [:index]
  end
  get "/:locale", to: "home#show", as: "home"
  root "home#show"
end

app/models/project_category.rb
# frozen_string_literal: true

class ProjectCategory < ApplicationRecord
  belongs_to :parent, class_name: "ProjectCategory", optional: true
  has_many :children, -> { order(:position) }, class_name: "ProjectCategory", foreign_key: :parent_id, dependent: :nullify, inverse_of: :parent
  has_many :projects, dependent: :destroy
  acts_as_list scope: :parent
  translates :name

  validates :name_en, presence: true
  validates :name_el, presence: true
  validates :slug, presence: true, uniqueness: true, slug: true
  validate :parent_assignment

  scope :roots, -> { where(parent_id: nil).includes(:children).order(:position) }

  def root?
    parent_id.blank?
  end

  def leaf?
    parent_id.present?
  end

  def to_s
    name
  end

  private

  def parent_assignment
    return unless parent

    if parent == self
      errors.add(:parent_id, :not_self)
    elsif parent.leaf?
      errors.add(:parent_id, :not_root)
    elsif children.any?
      errors.add(:parent_id, :assigned_children)
    end
  end
end

app/controllers/admin/project_categories_controller.rb
# frozen_string_literal: true

module Admin
  class ProjectCategoriesController < Admin::BaseController
    before_action :authorize_resource_access, only: %i[index new create]
    before_action :set_project_category, only: %i[show edit update destroy]
    before_action :set_parent_categories, only: %i[new create edit update]

    def index
      @project_categories = ProjectCategory.roots
    end

    def new
      @project_category = ProjectCategory.new
    end

    def create
      @project_category = ProjectCategory.new(project_category_params)
      if @project_category.save
        track_activity @project_category
        redirect_to [:admin, @project_category], notice: t(".success")
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @project_category.update(project_category_params)
        track_activity @project_category
        redirect_to [:admin, @project_category], notice: t(".success")
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @project_category.destroy
      track_activity @project_category
      redirect_to admin_project_categories_url, notice: t(".success")
    end

    private

    def authorize_resource_access
      authorize(ProjectCategory)
    end

    def set_breadcrumbs
      add_breadcrumb("Project categories", admin_project_categories_path)
    end

    def set_project_category
      @project_category = ProjectCategory.find(params[:id])
      authorize(@project_category)
      add_breadcrumb(@project_category.name, admin_project_category_path(@project_category))
    end

    def set_parent_categories
      @parent_categories = ProjectCategory.roots.excluding(@project_category)
    end

    def project_category_params
      attributes = %i[name_en name_el parent_id]
      attributes.push(:slug) if Current.user.admin?
      params.require(:project_category).permit(*attributes)
    end
  end
end

app/views/admin/project_categories/_form.html.erb
<%= simple_form_for([:admin, @project_category]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="fieldset">
    <%= f.input :slug %>
    <%= f.input :parent_id, collection: @parent_categories, disabled: @project_category.children.any? %>
  </div>

  <div class="fieldset">
    <%= f.input :name_en %>
    <%= f.input :name_el %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save category" %>
    <% if project_category.new_record? %>
      <%= link_to "Cancel", admin_project_categories_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", admin_project_category_path(project_category), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/project_categories/_project_category.html.erb
<%= content_tag :li, id: dom_id(project_category), data: { sgid: project_category.to_sgid_param } do %>
  <div class="flex items-center py-3 space-x-2 text-sm border-b border-neutral-200 dark:border-neutral-800 cursor-move">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-neutral-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M8 9l4-4 4 4m0 6l-4 4-4-4" />
    </svg>

    <%= link_to project_category.name, admin_project_category_path(project_category), class: "link" %>
  </div>

  <% if project_category.root? %>
    <ul class="pl-8" data-sortable-target="list">
      <%= render project_category.children %>
    </ul>
  <% end %>
<% end %>

app/views/admin/project_categories/edit.html.erb
<header class="page-header">
  <h1><%= title "Editing category" %></h1>
  <%= link_to "Show category", admin_project_category_path(@project_category), class: "ml-auto btn btn-primary" %>
</header>

<%= render "form", project_category: @project_category %>

app/views/admin/project_categories/index.html.erb
<header class="page-header">
  <h1><%= title "Project categories" %></h1>
  <%= link_to "New category", new_admin_project_category_path, class: "ml-auto btn btn-primary" if policy(ProjectCategory).create? %>
</header>

<div data-controller="sortable" data-sortable-url-value="<%= admin_sortables_path %>">
  <ul data-sortable-target="list">
    <%= render @project_categories %>
  </ul>
</div>

app/views/admin/project_categories/new.html.erb
<header class="page-header">
  <h1><%= title "New category" %></h1>
</header>

<%= render "form", project_category: @project_category %>

app/views/admin/project_categories/show.html.erb
<header class="page-header">
  <h1><%= title "Category details" %></h1>
  <%= link_to "Edit category", edit_admin_project_category_path(@project_category), class: "ml-auto btn btn-primary" if policy(@project_category).update? %>
  <%= button_to "Delete category", admin_project_category_path(@project_category), method: :delete, class: "ml-4 btn btn-danger", form: { data: { turbo_confirm: "Are you sure you want to delete this category?" } } if policy(@project_category).destroy? %>
</header>

<%= show_for @project_category do |s| %>
  <%= s.attribute :slug %>
  <%= s.attribute :name_en %>
  <%= s.attribute :name_el %>
  <%= s.association :parent %>
  <%= s.attribute :projects do %>
    <% if @project_category.projects_count.zero? %>
      <span class="text-neutral-500 italic">No projects associated with this category.</span>
    <% else %>
      <%= link_to pluralize(@project_category.projects_count, "project"), admin_projects_path(category_id: @project_category.id), class: "link" %>
    <% end %>
  <% end %>
  <%= s.attribute :created_at do %>
    <%= local_time @project_category.created_at, format: :long %>
  <% end %>
  <%= s.attribute :updated_at do %>
    <%= local_time @project_category.updated_at, format: :long %>
  <% end %>
  <%= s.attribute :history do %>
    <%= render "admin/activities/history", trackable: @project_category %>
  <% end %>
<% end %>