config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Auth routes
  get "/login", to: "auth/sessions#new", as: "login"
  post "/login", to: "auth/sessions#create"
  get "/logout", to: "auth/sessions#destroy", as: "logout"

  # Admin routes
  namespace :admin do
    resources :pages
    resources :snippets
    resources :article_categories
    resources :articles
    resources :product_categories
    resources :suppliers
    resources :products
    resources :project_categories
    resources :projects
    resources :activities, only: %i[index]
    resources :users
    resources :sortables, only: %i[create]
    resource :profile, only: %i[show update]
    root "dashboard#show"
  end

  # Public routes
  scope "(:locale)", locale: /en|el/ do
    resources :articles, only: [:index]
  end
  get "/:locale", to: "home#show", as: "home"
  root "home#show"
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: %i[title_en title_el body_en body_el tags], using: { tsearch: { prefix: true } }
  belongs_to :product_category, counter_cache: true
  belongs_to :supplier, counter_cache: true
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [96, 96]
  end
  enum status: { draft: 0, published: 1 }
  translates :title, :body

  before_validation :set_published_on

  validates :title_en, presence: true
  validates :title_el, presence: true
  validates :body_en, presence: true
  validates :body_el, presence: true
  validates :status, presence: true
  validate :product_category_level

  scope :matching, ->(term) { search(term) if term.present? }
  scope :in_category, ->(id) { where(product_category_id: id) if id.present? }
  scope :by_supplier, ->(id) { where(supplier_id: id) if id.present? }
  scope :with_status, ->(value) { where(status: value) if value.present? }

  def to_s
    title
  end

  private

  def set_published_on
    if published?
      self.published_on ||= Time.zone.today
    else
      self.published_on = nil
    end
  end

  def product_category_level
    errors.add(:product_category, :root) if product_category&.root?
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::BaseController
    before_action :authorize_resource_access, only: %i[index new create]
    before_action :set_product, only: %i[show edit update destroy]

    def index
      products = Product.
                 includes(:product_category, :supplier).
                 matching(params[:query]).
                 in_category(params[:category_id]).
                 by_supplier(params[:supplier_id]).
                 with_status(params[:status]).
                 order(id: :desc)
      @pagy, @products = pagy(products)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        track_activity @product
        redirect_to [:admin, @product], notice: t(".success")
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show; end

    def edit; end

    def update
      if @product.update(product_params)
        track_activity @product
        redirect_to [:admin, @product], notice: t(".success")
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy
      track_activity @product
      redirect_to admin_products_url, notice: t(".success")
    end

    private

    def authorize_resource_access
      authorize(Product)
    end

    def set_breadcrumbs
      add_breadcrumb("Products", admin_products_path)
    end

    def set_product
      @product = Product.find(params[:id])
      authorize(@product)
      add_breadcrumb(@product.title, admin_product_path(@product))
    end

    def product_params
      params.require(:product).permit(:product_category_id, :supplier_id, :title_en, :title_el, :body_en, :body_el, :status, :published_on, images: [])
    end
  end
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, product]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="fieldset">
    <%= f.association :product_category, collection: ProductCategory.roots, as: :grouped_select, group_method: :children %>
    <%= f.association :supplier, collection: Supplier.order(:name) %>
  </div>

  <div class="fieldset">
    <%= f.input :title_en, wrapper_html: { class: "col-span-2" } %>
    <%= f.input :body_en, wrapper: :rich_editor %>
  </div>

  <div class="fieldset">
    <%= f.input :title_el, wrapper_html: { class: "col-span-2" } %>
    <%= f.input :body_el, wrapper: :rich_editor %>
  </div>

  <div class="fieldset" data-controller="publication" data-publication-control-value="published">
    <%= f.input :status, collection: Article.statuses.keys, label_method: :titleize, input_html: { data: { action: "change->publication#toggleDateFields" } } %>
    <%= f.input :published_on, include_blank: true, wrapper_html: { class: ("hidden" unless f.object.published?), data: { publication_target: "dateFields" } } %>
  </div>

  <div class="fieldset">
    <%= f.input :images, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save product" %>
    <% if product.new_record? %>
      <%= link_to "Cancel", admin_products_path, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Cancel", admin_product_path(product), class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<%= content_tag :tr, id: dom_id(product), class: dom_class(product) do %>
  <td class="td">
    <%= link_to product.title, admin_product_path(product), class: "link", data: { turbo_frame: "_top" } %>
  </td>
  <td class="td">
    <%= product.product_category %>
  </td>
  <td class="td">
    <%= product.supplier %>
  </td>
  <td class="td td-badge">
    <%= badge_for product.status %>
  </td>
  <td class="td td-time">
    <%= l product.created_at, format: :short %>
  </td>
  <td class="td td-actions">
    <ul class="row-actions">
      <% if policy(product).update? %>
        <li>
          <%= link_to "Edit", edit_admin_product_path(product), class: "link", data: { turbo_frame: "_top" } %>
        </li>
      <% end %>

      <% if policy(product).destroy? %>
        <li>
          <%= button_to "Delete", admin_product_path(product), method: :delete, class: "link link-danger", form: { data: { turbo_confirm: "Are you sure you want to delete this product?" } } %>
        </li>
      <% end %>
    </ul>
  </td>
<% end %>

app/views/admin/products/edit.html.erb
<header class="page-header">
  <h1><%= title "Editing product" %></h1>
  <%= link_to "Show product", admin_product_path(@product), class: "ml-auto btn btn-primary" %>
</header>

<%= render "form", product: @product %>

app/views/admin/products/index.html.erb
<header class="page-header">
  <h1><%= title "Products" %></h1>
  <%= link_to "New product", new_admin_product_path, class: "ml-auto btn btn-primary" if policy(Product).create? %>
</header>

<%= form_with url: "", method: "get", data: { turbo_frame: "products", turbo_action: "advance", controller: "search" } do |f| %>
  <div class="flex py-3 space-x-2 border-b border-neutral-200 dark:border-neutral-800">
    <%= f.search_field :query, placeholder: "Search...", value: params[:query], class: "field-input", data: { action: "input->search#submit" } %>
    <%= f.grouped_collection_select :category_id, ProductCategory.roots, :children, :name, :id, :name, { include_blank: "Category...", selected: params[:category_id] }, class: "w-48 field-input", data: { action: "change->search#submit" } %>
    <%= f.collection_select :supplier_id, Supplier.order(:name), :id, :name, { include_blank: "Supplier...", selected: params[:supplier_id] }, class: "w-48 field-input", data: { action: "change->search#submit" } %>
    <%= f.collection_select :status, Product.statuses.keys, :to_s, :titleize, { include_blank: "Status...", selected: params[:status] }, class: "w-auto field-input", data: { action: "change->search#submit" } %>
  </div>
<% end %>

<%= turbo_frame_tag "products" do %>
  <% if @pagy.count.zero? %>
    <div class="my-4 h-32 flex flex-col items-center justify-center border-4 border-dashed rounded-md border-neutral-300">
      <p class="text-sm text-neutral-500">
        No products were found.
        <%= link_to new_admin_product_path, class: "inline-flex link", data: { turbo_frame: "_top" } do %>
          <span>Add a new one</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="ml-1 h-5 w-5 text-indigo-500" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        <% end if policy(Product).create? %>
      </p>
    </div>
  <% else %>
    <table class="table table-index">
      <thead>
        <tr>
          <th class="th">Title</th>
          <th class="th">Category</th>
          <th class="th">Supplier</th>
          <th class="th th-badge">Status</th>
          <th class="th th-time">Created</th>
          <th class="th th-actions">Actions</th>
        </tr>
      </thead>

      <tbody>
        <%= render @products %>
      </tbody>
    </table>

    <%== pagy_nav(@pagy) %>
  <% end %>
<% end %>

app/views/admin/products/new.html.erb
<header class="page-header">
  <h1><%= title "New product" %></h1>
</header>

<%= render "form", product: @product %>

app/views/admin/products/show.html.erb
<header class="page-header">
  <h1><%= title "Product details" %></h1>
  <%= link_to "Edit product", edit_admin_product_path(@product), class: "ml-auto btn btn-primary" if policy(@product).update? %>
  <%= button_to "Delete product", admin_product_path(@product), method: :delete, class: "ml-4 btn btn-danger", form: { data: { turbo_confirm: "Are you sure you want to delete this product?" } } if policy(@product).destroy? %>
</header>

<%= show_for @product do |s| %>
  <%= s.attribute :title_en %>
  <%= s.attribute :body_en do %>
    <%= markdown @product.body_en %>
  <% end %>
  <%= s.attribute :title_el %>
  <%= s.attribute :body_el do %>
    <%= markdown @product.body_el %>
  <% end %>
  <%= s.attribute :images do %>
    <%= sortable_thumbnails_for @product %>
  <% end %>
  <%= s.attribute :product_category do %>
    <%= link_to @product.product_category, admin_product_category_path(@product.product_category), class: "link" %>
  <% end %>
  <%= s.attribute :supplier do %>
    <%= link_to @product.supplier, admin_supplier_path(@product.supplier), class: "link" %>
  <% end %>
  <%= s.attribute :status do %>
    <%= badge_for @product.status %>
  <% end %>
  <%= s.attribute :published_on %>
  <%= s.attribute :created_at do %>
    <%= local_time @product.created_at, format: :long %>
  <% end %>
  <%= s.attribute :updated_at do %>
    <%= local_time @product.updated_at, format: :long %>
  <% end %>
  <%= s.attribute :history do %>
    <%= render "admin/activities/history", trackable: @product %>
  <% end %>
<% end %>